#!/usr/bin/env ansible-playbook

- hosts: localhost
  become: no
  gather_facts: no

  vars_files:
    - secrets.yml

  vars:
    SSH_ALIAS: "ya16sdb"
    SSH_KEY_NAME: "ya16sdb"
    SSH_KEY_FILE: "~/.ssh/ya16sdb.pem"
    SERVER_NAME:
    SERVER_IP: "35.155.170.9"

    CLOUDFORMATION_PARAMS:
      KeyName: "{{ SSH_KEY_NAME }}"
      AMIId: "ami-db710fa3"
      InstanceType: "t2.medium"
      # defined by task 'set_eip_id' below:
      ElasticIPAllocationId: "{{ EIP_ALLOCATION_ID }}"

  tasks:
    - fail: msg="ansible version is {{ ansible_version['full'] }}, requires >= 2.7"
      when: ansible_version['full'] is version('2.7', '<')
      tags:
        - always
        - ansible-version

    - name: define EIP_ALLOCATION_ID
      set_eip_id:
        server_ip: "{{ SERVER_IP }}"
        # server_name: "{{ SERVER_NAME }}"

    - name: deploy the cloudformation template for this stack
      cloudformation:
        stack_name: "ya16sdb"
        state: "present"
        region: "us-west-2"
        template: "ya16sdb-stack.json"
        template_parameters: "{{ CLOUDFORMATION_PARAMS }}"

    # run using -e ssh_config=yes -t ssh-config
    - name: install ssh private key to ~/.ssh
      copy:
        content: "{{ SSH_PRIVATE_KEY }}"
        dest: "{{ SSH_KEY_FILE }}"
        owner: "{{ lookup('env', 'USER') }}"
        mode: "0600"
      when: ssh_config is defined and ssh_config == 'yes'
      tags:
        - ssh-config

    # run using -e ssh_config=yes -t ssh-config
    - name: add ssh configuration for this target to ~/.ssh/config
      blockinfile:
        create: yes
        backup: yes
        dest: ~/.ssh/config
        marker: "# {mark} added by ya16sdb/deploy/deploy.yml"
        content: |
          Host {{ SSH_ALIAS }}
            HostName {{ SERVER_NAME or SERVER_IP }}
            User ubuntu
            IdentityFile {{ SSH_KEY_FILE }}
      when: ssh_config is defined and ssh_config == 'yes'
      tags:
        - ssh-config

# required for ubuntu 16.04 to ensure python is installed
- hosts: "webserver"
  become: yes
  gather_facts: no
  pre_tasks:
    - raw: "sudo apt-get update && sudo apt-get -y install python-simplejson"

- hosts: "webserver"
  become: yes

