#!/usr/bin/env ansible-playbook

- hosts: localhost
  become: no
  gather_facts: no

  vars_files:
    - secrets.yml

  vars:
    STACK_NAME: "ya16sdb"
    SSH_ALIAS: "ya16sdb"
    SSH_KEY_NAME: "ya16sdb"
    SSH_KEY_FILE: "~/.ssh/ya16sdb.pem"
    SERVER_NAME:
    SERVER_IP: "35.155.170.9"

    CLOUDFORMATION_PARAMS:
      KeyName: "{{ SSH_KEY_NAME }}"
      AMIId: "ami-db710fa3"
      InstanceType: "t2.small"
      # defined by task 'set_eip_id' below:
      # ElasticIPAllocationId: "{{ EIP_ALLOCATION_ID }}"

  tasks:
    - fail: msg="ansible version is {{ ansible_version['full'] }}, requires >= 2.7"
      when: ansible_version['full'] is version('2.7', '<')
      tags:
        - always
        - ansible-version

    - name: deploy the cloudformation template for this stack
      cloudformation:
        stack_name: "{{ STACK_NAME }}"
        state: "present"
        region: "us-west-2"
        template: "ya16sdb-stack.json"
        template_parameters: "{{ CLOUDFORMATION_PARAMS }}"

    # run using -e ssh_config=yes -t ssh-config
    - name: install ssh private key to ~/.ssh
      copy:
        content: "{{ SSH_PRIVATE_KEY }}"
        dest: "{{ SSH_KEY_FILE }}"
        owner: "{{ lookup('env', 'USER') }}"
        mode: "0600"
      when: ssh_config is defined and ssh_config == 'yes'
      tags:
        - ssh-config

    - name: define INSTANCE_IP
      set_instance_ip:
        stack_name: "{{ STACK_NAME }}"
      tags: ssh-config

    - name: print INSTANCE_IP
      command: echo {{ INSTANCE_IP }}
      tags: ssh-config

    # run using -e ssh_config=yes -t ssh-config
    - name: add ssh configuration for this target to ~/.ssh/config
      blockinfile:
        create: yes
        backup: yes
        dest: ~/.ssh/config
        marker: "# {mark} added by ya16sdb/deploy/deploy.yml"
        content: |
          Host {{ SSH_ALIAS }}
            HostName {{ INSTANCE_IP }}
            User ubuntu
            IdentityFile {{ SSH_KEY_FILE }}
            StrictHostKeyChecking no
      # when: ssh_config is defined and ssh_config == 'yes'
      tags:
        - ssh-config

